  name: PyLint
  on:
    pull_request:
      paths:
        - '**.py'

  permissions:
    contents: read

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - id: changes
        uses: trilom/file-changes-action@v1.2.4
      - name: Report
        run: echo "Changed files ${{ steps.changes.outputs.files }}"
